check50:
  dependencies:
    - flask_session
  files:
    - !exclude "*.pyc"
    - !exclude __pycache__
    - !include application.py
    - !include finance.db
    - !include helpers.py
    - !include finance.zip
